apiVersion: v1
kind: Service
metadata:
  name: redis-scheduler
  namespace: production
  labels:
    app: redis-scheduler
spec:
  selector:
    app: redis-scheduler
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
