apiVersion: v1
kind: Service
metadata:
  name: keydb
  namespace: production
  labels:
    app: keydb
spec:
  selector:
    app: keydb
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
