apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >
    {
  "auths": {
    "revolutio.azurecr.io": {
      "username": "dummyuser",
      "password": "dummypassword123",
      "email": "dummy@example.com",
      "auth": "ZGVzdHJpbmcxY2VlcGVhdGNyLm91bnBxbg==" 
    }
  }
}
