apiVersion: v1
kind: Service
metadata:
  name: postgres-new
  namespace: production
  labels:
    app: postgres-new
spec:
  selector:
    app: postgres-new
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
